import { DecisionEntry } from '../data/types';

const sampleDecisions: DecisionEntry[] = [
  {
    id: 'seed-1',
    date: '2025-01-15T10:30:00.000Z',
    ticker: 'AAPL',
    companyName: 'Apple Inc.',
    decision: 'BUY',
    positionSizePercent: 15,
    positionSizeAmount: 15000,
    entryPriceTarget: 178.5,
    currentPrice: 212.3,
    reasoning: 'Strong ecosystem moat, services revenue growing 20% YoY, iPhone cycle looks promising with AI features. P/E reasonable at 28x given growth trajectory.',
    expectedOutcome: 'Target $220 within 12 months based on services multiple expansion',
    exitPlan: 'Sell 50% at $220, trail stop at 15% for remainder',
    reviewDates: ['2025-02-15', '2025-03-15', '2025-04-15'],
    scores: { buffett: 85, munger: 80, lynch: 75, rothschild: 70, overall: 78 },
    alertsSet: ['price-target', 'earnings'],
    status: 'closed',
    actualOutcome: 'Hit target price of $212, sold position for 18.9% gain',
    lessonsLearned: 'Patience paid off. Initial dip to $165 was scary but thesis held.',
  },
  {
    id: 'seed-2',
    date: '2025-02-20T14:00:00.000Z',
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    decision: 'BUY',
    positionSizePercent: 10,
    positionSizeAmount: 10000,
    entryPriceTarget: 680,
    currentPrice: 950,
    reasoning: 'AI infrastructure spending accelerating. Data center revenue tripled. Competitive moat in CUDA ecosystem is nearly unbreakable.',
    expectedOutcome: 'Target $900+ as AI capex cycle continues through 2025',
    exitPlan: 'Hold core position, trim 25% above $950',
    reviewDates: ['2025-03-20', '2025-04-20'],
    scores: { buffett: 70, munger: 85, lynch: 90, rothschild: 80, overall: 81 },
    alertsSet: ['earnings', 'sector-news'],
    status: 'closed',
    actualOutcome: 'Exceeded target significantly. AI demand stronger than expected.',
    lessonsLearned: 'Should have sized larger given conviction level. Fear of valuation held me back.',
  },
  {
    id: 'seed-3',
    date: '2025-03-10T09:00:00.000Z',
    ticker: 'TSLA',
    companyName: 'Tesla Inc.',
    decision: 'PASS',
    positionSizePercent: 0,
    positionSizeAmount: 0,
    entryPriceTarget: 250,
    currentPrice: 180,
    reasoning: 'Valuation too stretched at 80x forward earnings. Competition intensifying in EV space. Margin compression likely as price cuts continue.',
    expectedOutcome: 'Expect pullback to $180-200 range before reconsidering',
    exitPlan: 'N/A - not entering position',
    reviewDates: ['2025-04-10'],
    scores: { buffett: 35, munger: 40, lynch: 55, rothschild: 60, overall: 48 },
    alertsSet: [],
    status: 'closed',
    actualOutcome: 'Stock dropped to $180 as predicted. Good pass decision.',
    lessonsLearned: 'Trust the valuation framework even when momentum is strong.',
  },
  {
    id: 'seed-4',
    date: '2025-04-05T11:00:00.000Z',
    ticker: 'MSFT',
    companyName: 'Microsoft Corporation',
    decision: 'BUY',
    positionSizePercent: 12,
    positionSizeAmount: 12000,
    entryPriceTarget: 410,
    currentPrice: 390,
    reasoning: 'Azure growth reaccelerating with AI workloads. Copilot monetization beginning. Diversified revenue streams provide downside protection.',
    expectedOutcome: 'Target $450 within 6 months on cloud growth',
    exitPlan: 'Stop loss at $370, take profit at $450',
    reviewDates: ['2025-05-05', '2025-06-05'],
    scores: { buffett: 82, munger: 78, lynch: 72, rothschild: 75, overall: 77 },
    alertsSet: ['price-target', 'earnings'],
    status: 'active',
    actualOutcome: '',
    lessonsLearned: '',
  },
  {
    id: 'seed-5',
    date: '2025-04-20T08:30:00.000Z',
    ticker: 'AMZN',
    companyName: 'Amazon.com Inc.',
    decision: 'WATCHLIST',
    positionSizePercent: 0,
    positionSizeAmount: 0,
    entryPriceTarget: 170,
    currentPrice: 185,
    reasoning: 'AWS margins expanding, advertising business growing fast. Want to enter on a pullback to $170 level for better risk/reward.',
    expectedOutcome: 'Wait for pullback to $170 support level',
    exitPlan: 'Enter at $170, stop at $155, target $210',
    reviewDates: ['2025-05-20'],
    scores: { buffett: 75, munger: 80, lynch: 82, rothschild: 78, overall: 79 },
    alertsSet: ['price-alert'],
    status: 'active',
    actualOutcome: '',
    lessonsLearned: '',
  },
  {
    id: 'seed-6',
    date: '2025-01-28T13:00:00.000Z',
    ticker: 'META',
    companyName: 'Meta Platforms Inc.',
    decision: 'BUY',
    positionSizePercent: 8,
    positionSizeAmount: 8000,
    entryPriceTarget: 480,
    currentPrice: 420,
    reasoning: 'Reels monetization improving, Reality Labs losses narrowing. Strong ad revenue growth from AI-powered targeting.',
    expectedOutcome: 'Target $550 on continued ad revenue growth',
    exitPlan: 'Stop loss at $430, hold for 12 months',
    reviewDates: ['2025-02-28', '2025-03-28'],
    scores: { buffett: 65, munger: 70, lynch: 78, rothschild: 72, overall: 71 },
    alertsSet: ['earnings'],
    status: 'closed',
    actualOutcome: 'Stock dropped to $420 on Reality Labs concerns. Stopped out for -12.5% loss.',
    lessonsLearned: 'Should have waited for better entry. FOMO led to chasing at highs.',
  },
  {
    id: 'seed-7',
    date: '2025-03-25T10:00:00.000Z',
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    decision: 'BUY',
    positionSizePercent: 10,
    positionSizeAmount: 10000,
    entryPriceTarget: 155,
    currentPrice: 140,
    reasoning: 'Search moat intact despite AI fears. Cloud growing 28%. YouTube ad revenue strong. Trading at discount to peers.',
    expectedOutcome: 'Target $180 as AI narrative shifts positive',
    exitPlan: 'Stop at $140, target $180',
    reviewDates: ['2025-04-25', '2025-05-25'],
    scores: { buffett: 78, munger: 82, lynch: 70, rothschild: 74, overall: 76 },
    alertsSet: ['price-target', 'sector-news'],
    status: 'closed',
    actualOutcome: 'Hit stop loss at $140. AI competition fears drove selloff.',
    lessonsLearned: 'Underestimated market sentiment around AI disruption narrative. Need to factor in narrative risk.',
  },
  {
    id: 'seed-8',
    date: '2025-05-01T09:00:00.000Z',
    ticker: 'JPM',
    companyName: 'JPMorgan Chase & Co.',
    decision: 'BUY',
    positionSizePercent: 8,
    positionSizeAmount: 8000,
    entryPriceTarget: 195,
    currentPrice: 210,
    reasoning: 'Best-in-class bank with strong NII outlook. Trading below historical P/E. Dividend yield attractive at 2.5%.',
    expectedOutcome: 'Target $225 on rate environment normalization',
    exitPlan: 'Hold for dividend + appreciation, review quarterly',
    reviewDates: ['2025-06-01', '2025-07-01'],
    scores: { buffett: 80, munger: 75, lynch: 68, rothschild: 82, overall: 76 },
    alertsSet: ['earnings', 'dividend'],
    status: 'active',
    actualOutcome: '',
    lessonsLearned: '',
  },
];

export function seedJournalData(): void {
  localStorage.setItem('investment_decisions', JSON.stringify(sampleDecisions));
  console.log(`✅ Seeded ${sampleDecisions.length} sample decisions into localStorage`);
}

export function clearJournalData(): void {
  localStorage.removeItem('investment_decisions');
  console.log('🗑️ Cleared journal data from localStorage');
}
